version: '2'
services:
  app:
    image: ameizi/spring-boot-docker-example
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db:database
    volumes:
      - /tmp:/tmp
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /Users/feng/mysql/data:/var/lib/mysql